name: CICD

on:
  push:
    branches:
    - main
    - D-*
    paths:
    - show-ip/**
  pull_request:
    branches:
    - main

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  CICD:
    uses: ./.github/workflows/cicd.yaml
    with:
      app_name: show-ip
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
