name: Docker Build and Push for Modified Folders

on:
  push:
    branches:
      - main
      - DEV-*
    paths:
      - show-ip/**
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Login to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build and push the Docker image
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: show-ip/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/show-ip:latest

    # Verify that the Docker image is built
    - name: Image digest
      run: echo ${{ steps.build.outputs.digest }}
      