name: CICD

on:
  push:
    branches:
    - main
    - D-*
    paths:
    - gha-runner/**
  pull_request:
    branches:
    - main

jobs:
  CICD:
    uses: ./.github/workflows/cicd.yaml
    with:
      app_name: gha-runner
