name: Reusable Workflow Post Deployment

on:
  workflow_call:
    inputs:
      build_args:
        type: string
        description: List of build args for Docker build
        default: ""
        required: false
        
jobs:
  PD:
    runs-on: ubuntu-latest
    steps:

    - name: Post deployment
      run: |
        echo "Running Post Deployment..."